### ISSUE TITLE
Unable to install with latest pip version

### ISSUE THREAD

**Issue by steven-luabase** [storebrand/tap-sharepointsites#8]
Running into an issue that just started yesterday (June 20, 2024) while trying to install tap-sharepointsites from the github repo. This is the command I'm running `meltano install extractor tap-sharepointsites` and this is my yml config:

```
- name: tap-sharepointsites
    variant: storebrand
    pip_url: git+https://github.com/storebrand/tap-sharepointsites.git
```

I'm getting the following error which seems to indicate pip 0.24.1 (released yesterday) is the issue:
```
Requested textract<2.0.0,>=1.6.4 from https://files.pythonhosted.org/packages/6b/3e/ac16b6bf28edf78296aea7d0cb416b49ed30282ac8c711662541015ee6f3/textract-1.6.5-py3-none-any.whl (from tap-sharepointsites==1.2.0) has invalid metadata: .* suffix can only be used with `==` or `!=` operators
    extract-msg (<=0.29.*)
                 ~~~~~~~^
Please use pip<24.1 if you need to use this version.
```

I tried a clean install of tap-sharepointsites outside of meltano with pip 24.0 and it works whereas installing with 24.1 throws the same error, so I'm pretty sure the new version of pip is the issue here. Is there a way to ensure this tap gets installed with pip < 24.1 or is there another way to get around this?

**Comment by eivind-stb** [comment]
Sorry for the late reply, but we've moved on from Meltano and are no longer maintaining this repository.
